version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/app/api
    env_file:
      - .env
    ports:
      - "8080:8080"
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: [ "tools" ]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
      ]
    command: [ "up" ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: